use_frameworks!

platform :ios, '14.0'

target 'DesignKit_Example' do
  pod 'DesignKit', :path => '../'

  target 'DesignKit_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
